[package]
name = "day20"
version = "0.1.0"
authors = ["Alejandro Rivero Perez <nubcrack@yahoo.es>"]
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html
[dependencies]
substring = "*"
queues = "*"